import Link from 'next/link';
import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import './globals.css';


const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Future World",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <ul>
            <li>
              <Link href="/">
                Home
              </Link>
            </li>
            <li>
              <Link href="/store">
                Store
              </Link>
            </li>
          </ul>
        </header>
        {children}
      </body>
    </html>
  );
}
